# Generated by Django 4.2.3 on 2023-07-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Movie',
        ),
    ]
