# Generated by Django 4.2.3 on 2023-07-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_place_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='asdf', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
